### ISSUE TITLE
Remove Lorem Ipsum and add meaningful content

### ISSUE THREAD

**Issue by SecureSocket** [SecureSocket/hacktoberfest2023-WebDev#206]

**Comment by sulavghimiree** [comment]
I will do it @SecureSocket . Assign this to me

**Comment by MeetD99** [comment]
I would like to work on this issue, can you please assign me this?

**Comment by AkshatJangid787** [comment]
can you please assign me this?

**Comment by AkshatJangid787** [comment]
I solved this issue kindly review it and tell me fixes required.

**Comment by RahulSoni2532** [comment]
by mistake my assignment was canceled please reassign me @SecureSocket
