### ISSUE TITLE
Fix Contributors Page Issue

### ISSUE THREAD

**Issue by SecureSocket** [SecureSocket/hacktoberfest2023-WebDev#208]

**Comment by monicknog** [comment]
I would like to work on this issue

**Comment by insane-22** [comment]
Hello! 
I've solved the error locally and would like to contribute to your project under hacktoberfest.
Kindly assign this issue to me.
Thank you for your consideration
![image](https://github.com/SecureSocket/hacktoberfest2023-WebDev/assets/116253210/930863c4-f69f-4b7c-a9f9-eea94d817682)
