### ISSUE TITLE
Icons problem in web.

### ISSUE THREAD

**Issue by tribhuwan-kumar** [SecureSocket/hacktoberfest2023-WebDev#218]
### Menu toggle icon is disappeared in mobile devices:
![image](https://github.com/SecureSocket/hacktoberfest2023-WebDev/assets/118052427/7b3db7f2-610e-4976-b09a-3dbe522eaaae)
### Icons should be updated: 
![image](https://github.com/SecureSocket/hacktoberfest2023-WebDev/assets/118052427/d0038d37-7f35-4992-985c-fc733244de69)
![image](https://github.com/SecureSocket/hacktoberfest2023-WebDev/assets/118052427/4c1b2ee8-da1d-49c6-9ab1-ef6a42d49bc7)
### There is no favicon in about page and blog page:
![image](https://github.com/SecureSocket/hacktoberfest2023-WebDev/assets/118052427/c00b3b22-9acc-4b59-8e9f-c5542404b922)
![image](https://github.com/SecureSocket/hacktoberfest2023-WebDev/assets/118052427/fe3073db-cb2d-463e-b339-95000ca0bec3)
## I'll fix it please assign me!!

**Comment by HarshikaAdarsh** [comment]
Hey @tribhuwan-kumar and @SecureSocket  I'm interested in working on it. Would it be possible to assign this issue to

**Comment by tribhuwan-kumar** [comment]
I already did it work on another issue

**Comment by HarshikaAdarsh** [comment]
> I already did it work on another issue

okay
