### ISSUE TITLE
No link to brand name in footer

### ISSUE THREAD

**Issue by rohit192ranjan** [SecureSocket/hacktoberfest2023-WebDev#225]
Brand name in footer have no link it should scroll up to navbar.
![image](https://github.com/SecureSocket/hacktoberfest2023-WebDev/assets/105169794/0ed3ada6-f1d1-47f4-93a3-ec00d894cf66)

**Comment by rohit192ranjan** [comment]
@SecureSocket assign this to me, I'll fix it

**Comment by HarshikaAdarsh** [comment]
Hey @SecureSocket  I' would like to work on this issue. Please assign to me.

**Comment by rohit192ranjan** [comment]
@HarshikaAdarsh I've already fixed it and my pr is ready, so you can work on another one.

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by Sha1kh4** [comment]
@SecureSocket Please Check my PR.

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign me this issue.
